<?php

/**
 * Title: PayPal Payments Standard variables
 * Description:
 * Copyright: Copyright (c) 2005 - 2015
 * Company: Pronamic
 * @author Remco Tolsma
 * @version 1.0.0
 * @see https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/
 */
class Pronamic_WP_Pay_Gateways_PayPalPaymentsStandard_Variables {
	/**
	 * Indicator for the 'cmd' variable
	 *
	 * @var string
	 */
	const CMD = 'cmd';

	/**
	 * Indicator for the 'notify_url' variable
	 *
	 * The URL to which PayPal posts information about the payment, 
	 * in the form of Instant Payment Notification messages.
	 *
	 * @var string
	 */
	const NOTIFY_URL = 'notify_url';

	/**
	 * Indicator for the 'hosted_button_id' variable
	 *
	 * Required for buttons that have been saved in PayPal accounts; otherwise, not allowed.
	 * The identifier of a button that was saved in a merchant's PayPal account. PayPal assigns the value
	 * when payment buttons are first created and saved in merchants' PayPal accounts.
	 * Note: A merchant's PayPal account can have a maximum of 1,000 saved payment buttons.
	 *
	 * @var string
	 */
	const HOSTED_BUTTON_ID = 'hosted_button_id';

	/**
	 * Indicator for the 'bn' variable
	 *
	 * An identifier of the source that built the code for the button that the buyer clicked, 
	 * sometimes known as the build notation. Specify a value using the following format:
	 * `<Company>_<Service>_<Product>_<Country>`
	 * Substitute <Service> with an appropriate value from the following list:
	 *
	 * - BuyNow
	 * - AddToCart
	 * - Donate
	 * - Subscribe
	 * - AutomaticBilling
	 * - InstallmentPlan
	 * - BuyGiftCertifcate
	 * - ShoppingCart
	 *
	 * Substitute `<Product>` with WPS always for PayPal Payments Standard payment buttons and for the
	 * PayPal Payments Standard Cart Upload command.
	 *
	 * Substitute `<Country>` with an appropriate two-letter country code from codes defined by the ISO 3166-1 standard.
	 *
	 * For example, a Buy Now button on your website that you coded yourself might have the following line of code:
	 *
	 * `bn="DesignerFotos_BuyNow_WPS_US"`
	 *
	 * Note: HTML button code that you create on the PayPal website includes `bn` variables with valid values generated by PayPal.
	 *
	 * @var string
	 */
	const BN = 'bn';
}
